name: gl4u_intro_2024
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.10
  - pip
  - jupyterlab==4.2.5
  - notebook==6.5.5
  - bash_kernel==0.9.3
  - r-irkernel==1.3.2
  - coreutils
  - htslib
  - openssl
  - nodejs
  - r-base==4.3.2
  - r-tidyverse==2.0.0
  - fastqc==0.12.1
  - multiqc==1.24.1
  - pip
  - pip:
    - jupyter_contrib_nbextensions==0.7.0
    - jupyter_nbextensions_configurator==0.6.3
    - nbclassic==0.4.8
